# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end


# ServiceExtension Target
target 'ServiceExtension' do
  use_frameworks!
#    platform :ios, '10.0'
    pod 'WEServiceExtension'
end

# ContentExtension Target
target 'ContentExtension' do
  use_frameworks!
#  platform :ios, '10.0'
  pod 'WEContentExtension'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  ################  Awesome Notifications pod modification  ###################
  # Define the path to the Awesome Notifications pod script
  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')

  # Ensure the file exists before requiring it
  if File.exist?(awesome_pod_file)
    require awesome_pod_file
    # Update pod build settings
    update_awesome_pod_build_settings(installer)
    # Update main target settings
    update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
  else
    puts "Warning: Awesome Notifications pod file not found at #{awesome_pod_file}. Skipping configuration."
  end
  ################  Awesome Notifications pod modification  ###################
end
