name: webengage_flutter_web
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2
  webengage_flutter_platform_interface:
    path: ../webengage_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WEFlutterWeb
        fileName: webengage_flutter_web.dart
        dartPluginClass: WEFlutterWeb

