name: webengage_flutter_web
description: "The WebEngage Flutter SDK offers solutions for mobile customer engagement, analytics, and retention."
version: 2.0.0
homepage: https://webengage.com/
repository: https://github.com/WebEngage/webengage-flutter

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.0.2
  webengage_flutter_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: webengage_flutter
    platforms:
      web:
        pluginClass: WEFlutterWeb
        fileName: webengage_flutter_web.dart
        dartPluginClass: WEFlutterWeb

