name: webengage_flutter_ios
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  webengage_flutter_platform_interface:
    path: ../webengage_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: WebEngagePlugin
        dartPluginClass: WEFlutterIos


