name: dev_sample_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: 2.5.5

  cupertino_icons: ^1.0.2

  permission_handler:
  
  webengage_flutter:
    path: ../webengage_flutter
  webengage_flutter_location: ^1.0.0
  we_personalization_flutter: ^2.0.0
  we_notificationinbox_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^5.5.3

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true

