name: webengage_flutter
description: The WebEngage Flutter SDK offers solutions for mobile customer engagement, analytics, and retention.
version: 1.5.0
homepage: https://webengage.com/
repository: https://github.com/WebEngage/webengage-flutter

environment:
  sdk: ">2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  webengage_flutter_platform_interface:
    path: ../webengage_flutter_platform_interface
  webengage_flutter_android:
    path: ../webengage_flutter_android
  webengage_flutter_web:
    path: ../webengage_flutter_web



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: webengage_flutter_android
      ios:
        pluginClass: WebEngagePlugin
      web:
        default_package: webengage_flutter_web
