name: webengage_flutter_android
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  webengage_flutter_platform_interface:
    path: ../webengage_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: webengage_flutter
    platforms:
      android:
        package: com.webengage.webengage_plugin
        pluginClass: WebEngagePlugin
        dartPluginClass: WEFlutterAndroid

